{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hcevideocall\/hcecall\/callsessionconnectionevent\/failed"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/CallSessionConnectionEvent\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A “failed” event occurs when a connection is unsuccessful."},{"type":"text","text":" "},{"type":"text","text":"At this point, connection can be neither established nor restored, thus the SDK executes the “Room Leave” procedure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"title":"HceCall.CallSessionConnectionEvent.failed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12HceVideoCall0aC0C0C22SessionConnectionEventO6failedyA2EmF","modules":[{"name":"HceVideoCall"}]},"hierarchy":{"paths":[["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/CallSessionConnectionEvent"]]},"references":{"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall":{"role":"symbol","title":"HceCall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceCall"}],"abstract":[{"type":"text","text":"class HceCall"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceCall"}],"url":"\/documentation\/hcevideocall\/hcecall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall/CallSessionConnectionEvent/failed":{"role":"symbol","title":"HceCall.CallSessionConnectionEvent.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"A “failed” event occurs when a connection is unsuccessful."},{"type":"text","text":" "},{"type":"text","text":"At this point, connection can be neither established nor restored, thus the SDK executes the “Room Leave” procedure."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/CallSessionConnectionEvent\/failed","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/hcecall\/callsessionconnectionevent\/failed"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall/CallSessionConnectionEvent":{"role":"symbol","title":"HceCall.CallSessionConnectionEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallSessionConnectionEvent"}],"abstract":[{"type":"text","text":"Events that occur when the network connection status changes between “Join” and “Leave”."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/CallSessionConnectionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallSessionConnectionEvent"}],"url":"\/documentation\/hcevideocall\/hcecall\/callsessionconnectionevent"}}}